CREATE TABLE COURSE (
COURSEID VARCHAR(10),
COURSENAME VARCHAR(50),
YR NUMBER,
SEM NUMBER
);

CREATE TABLE COURSEMATERIALS (
COURSEID VARCHAR(10),
FILE_TITLE VARCHAR(75),
CONTENTFILE BLOB,
AUTHOR VARCHAR(75),
PUBLISHED_TIME TIMESTAMP
);

CREATE TABLE COURSEASSIGNMENTS (
COURSEID VARCHAR(10),
ASSIGN_TITLE VARCHAR(75),
ASSIGN_FILE BLOB,
AUTHOR VARCHAR(75),
PUBLISHED_TIME TIMESTAMP
);

CREATE TABLE COURSETESTS (
COURSEID VARCHAR(10),
TEST_TITLE VARCHAR(75),
TEST_FILE BLOB,
AUTHOR VARCHAR(75),
PUBLISHED_TIME TIMESTAMP
);

CREATE TABLE STUDENT (
REGID NUMBER,
FULLNAME VARCHAR(75),
PHONE VARCHAR(10),
EMAIL VARCHAR(50),
PASSWORD VARCHAR(50)
);

CREATE TABLE STUDENTCOURSES (
REGID NUMBER,
COURSEID VARCHAR(10)
);

CREATE TABLE FACULTY (
FACULTYID NUMBER,
FULLNAME VARCHAR(75),
PHONE VARCHAR(10),
EMAIL VARCHAR(50),
PASSWORD VARCHAR(50)
);

CREATE TABLE FACULTYCOURSES (
FACULTYID NUMBER,
COURSEID VARCHAR(10)
);

CREATE TABLE STULOGINDATA (
STUEMAIL VARCHAR(50),
STULOGINTIME TIMESTAMP
);

CREATE TABLE STULOGOUTDATA (
STUEMAIL VARCHAR(50),
STULOGOUTTIME TIMESTAMP
);

CREATE TABLE FACLOGINDATA (
FACEMAIL VARCHAR(50),
FACLOGINTIME TIMESTAMP
);

CREATE TABLE FACLOGOUTDATA (
FACEMAIL VARCHAR(50),
FACLOGOUTTIME TIMESTAMP
);

CREATE TABLE ADMINCRED (
ADMINUSERNAME varchar(50),
ADMINPASSWORD varchar(50)
);

INSERT INTO ADMINCRED VALUES ('admin','admin@1234');

insert into course values('19cs2201','Data Science',2,2);
insert into course values('20cs3215','C language',1,1);
insert into course values('17sc1984','ML Using Math',4,2);
insert into course values('18ME3210','Cyber Security',3,2);